// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: apikey.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (project_id, owner_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, owner_id, name, key_hash, key_prefix, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ProjectID pgtype.UUID
	OwnerID   pgtype.UUID
	Name      string
	KeyHash   string
	KeyPrefix string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.OwnerID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id, owner_id, name, key_hash, key_prefix, created_at, revoked_at FROM api_keys
WHERE key_hash = $1
  AND revoked_at IS NULL
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeysByOwner = `-- name: ListAPIKeysByOwner :many
SELECT id, project_id, owner_id, name, key_hash, key_prefix, created_at, revoked_at FROM api_keys
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByOwner(ctx context.Context, ownerID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT id, project_id, owner_id, name, key_hash, key_prefix, created_at, revoked_at FROM api_keys
WHERE project_id = $1
  AND owner_id = $2
ORDER BY created_at DESC
`

type ListAPIKeysByProjectParams struct {
	ProjectID pgtype.UUID
	OwnerID   pgtype.UUID
}

func (q *Queries) ListAPIKeysByProject(ctx context.Context, arg ListAPIKeysByProjectParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, arg.ProjectID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = NOW()
WHERE id = $1
  AND owner_id = $2
  AND revoked_at IS NULL
RETURNING id, project_id, owner_id, name, key_hash, key_prefix, created_at, revoked_at
`

type RevokeAPIKeyParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.OwnerID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
