// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: project.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (owner_id, name, slug, description, environment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, slug, description, environment, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID     pgtype.UUID
	Name        string
	Slug        string
	Description pgtype.Text
	Environment string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Environment,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, owner_id, name, slug, description, environment, created_at, updated_at FROM projects
WHERE id = $1 AND owner_id = $2
LIMIT 1
`

type GetProjectByIDParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByOwnerAndSlug = `-- name: GetProjectByOwnerAndSlug :one
SELECT id, owner_id, name, slug, description, environment, created_at, updated_at FROM projects
WHERE owner_id = $1 AND slug = $2
LIMIT 1
`

type GetProjectByOwnerAndSlugParams struct {
	OwnerID pgtype.UUID
	Slug    string
}

func (q *Queries) GetProjectByOwnerAndSlug(ctx context.Context, arg GetProjectByOwnerAndSlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByOwnerAndSlug, arg.OwnerID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByOwner = `-- name: ListProjectsByOwner :many
SELECT id, owner_id, name, slug, description, environment, created_at, updated_at FROM projects
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Environment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3,
    description = $4,
    updated_at = NOW()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, slug, description, environment, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID
	OwnerID     pgtype.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
